# Generated by Django 4.2.2 on 2023-06-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_rename_reviews_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='totalprice',
        ),
    ]
