# Generated by Django 4.2.2 on 2023-06-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_review_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='createdAt',
        ),
    ]
